Add SoftDot node
biaslab/ReactiveMP.jl pull request #305
Opened 2023-04-02 10:30 UTC by abpolym

This PR is regarding to issue #231 .

2023-04-03 11:22 UTC, albertpod commented on src/nodes/softdot.jl
> +@average_energy softdot (q_y::NormalDistributionsFamily, q_θ::NormalDistributionsFamily, q_x::NormalDistributionsFamily, q_γ::GammaShapeRate) = begin
You can safely use GammaDistributionFamily here.

I would suggest to remove multiline AE calculations and have smth like:

```julia
function average_energy(q_y::NormalDistributionsFamily, q_θ::NormalDistributionsFamily, q_x::NormalDistributionsFamily, q_γ::GammaDistributionsFamily)
    m_y, V_y = mean_cov(q_y)
    m_θ, V_θ = mean_cov(q_θ)
    m_x, V_x = mean_cov(q_x)
    m_γ = mean(q_γ)
    AE = -mean(log.(q_γ)) + log2π .+ m_γ .* (V_y + m_y.^2 .- 2m_γ * (m_θ'*m_x) .+ mul_trace(V_θ, V_x) .+ m_x' * V_θ * m_x .+ m_θ' * (V_x .+ m_x * m_x') * m_θ) ./ 2
    return AE
end
```

2023-04-03 11:57 UTC, albertpod requested changes
Look good @abpolym! I've left just a few comments.

Don't forget the about formatter and double-check `average_energy` tests. They are failing.

2023-04-03 11:57 UTC, albertpod commented on src/nodes/softdot.jl
> +end
You can safely use GammaDistributionFamily here.

I would suggest to remove multiline AE calculations and have smth like:

```julia
function average_energy(q_y::NormalDistributionsFamily, q_θ::NormalDistributionsFamily, q_x::NormalDistributionsFamily, q_γ::GammaDistributionsFamily)
    m_y, V_y = mean_cov(q_y)
    m_θ, V_θ = mean_cov(q_θ)
    m_x, V_x = mean_cov(q_x)
    m_γ = mean(q_γ)
    AE = -mean(log.(q_γ)) + log2π .+ m_γ .* (V_y + m_y.^2 .- 2m_γ * (m_θ'*m_x) .+ mul_trace(V_θ, V_x) .+ m_x' * V_θ * m_x .+ m_θ' * (V_x .+ m_x * m_x') * m_θ) ./ 2
    return AE
end
```

2023-04-03 11:57 UTC, albertpod commented on src/rules/softdot/gamma.jl
> +# Belief propagation: does not exist for softdot
Good comment, although then be consistent and say which kind of variational rule is available, i.e., mean-field variational message

2023-04-03 11:57 UTC, albertpod commented on src/rules/softdot/x.jl
> +    zx = mγ * mθ * my'
unnecessary scalar transpose

2023-04-06 12:21 UTC, albertpod approved these changes

2023-04-06 12:21 UTC, albertpod commented
@abpolym thanks for incorporating the comments. I approve.

2023-04-07 07:52 UTC, bvdmitri commented
Great work @abpolym ! Thanks!

2023-04-07 07:52 UTC, merged